// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
	aws_appsync_graphqlEndpoint:
		'https://tsil6utanbfdjpvyrgwikjhkne.appsync-api.us-east-2.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-2',
	aws_appsync_authenticationType: 'API_KEY',
	aws_appsync_apiKey: 'da2-ffyhq623szeavnvhk524nryhbi',
};

export default awsconfig;
